# file: roles/nginx/tasks/main.yml
- name: nginx install
  yum: name=nginx state=installed

- name: copy nginx.conf
  template: src=roles/nginx/templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart mysqld

- name: copy logrotate conf
  template: src=roles/nginx/templates/logrotate.j2 dest=/etc/logrotate.d/nginx

- name: nginx is running and enabled
  service: name=nginx state=running enabled=yes
