- hosts: test
  user: root
  sudo: yes
  tasks:
    - name: muninのインストール
      action: yum name=munin state=installed
    - name: nginxのインストール
      action: yum name=nginx state=installed
    - name: Nginxの設定ファイルを書き出し
      action: template src=src/nginx.conf dest=/etc/nginx/nginx.conf
