# file: roles/varnish/tasks/main.yml
- name: state directory
  file: state=directory path=/usr/local/src

- name: varnish download
  get_url: url=$url dest=/usr/local/src

- name: varnish extracted
  command: tar zxf varnish-3.0.3.tar.gz chdir=/usr/local/src creates=$path

- name: varnish configured
  command: ./configure --prefix=/usr/local/varnish chdir=$path

- name: varnish compiled
  command: make chdir=$path

- name: varnish install
  command: make install chdir=$path
