# file: roles/mysql/tasks/main.yml
- name: mysql-server install
  yum: name=mysql-server state=installed

- name: copy my.conf
  template: src=roles/mysql/templates/my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysqld

- name: mysqld is running and enabled
  service: name=mysqld state=running enabled=yes
