# file: roles/common/tasks/main.yml
- name: add rpmforge
  command: rpm --force -Uvh http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm creates=/etc/yum.repos.d/rpmforge.repo

- name: add remi
  command: rpm --force -Uvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm creates=/etc/yum.repos.d/remi.repo

- name: yum dependencies
  yum: name={{ item }} state=installed
  with_items:
    - epel-release
    - vim-enhanced
    - git
    - gcc-c++
    - autoconf
    - make
    - automake
    - wget
    - patch
    - readline-devel
    - zlib-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - gdbm-devel
    - tcl-devel
    - tk-devel
    - libxslt-devel
    - libxml2-devel
    - libyaml-devel
    - sqlite-devel
    - curl
    - libcurl-devel
    - ncurses-devel
    - pcre-devel
    - gd-devel
    - bind-utils
    - libselinux-python

