# file: roles/ruby/tasks/main.yml
- name: ruby state directory
  file: state=directory path=/usr/local/src

- name: ruby download
  get_url: url=$ruby_url dest=/usr/local/src

- name: ruby extracted
  command: tar zxf $ruby_version.tar.gz chdir=/usr/local/src creates=$ruby_path

- name: ruby configured
  command: ./configure chdir=$ruby_path creates=$ruby_path/Makefile

- name: ruby compiled
  command: make chdir=$ruby_path creates=$ruby_path/ruby

- name: ruby install
  command: make install chdir=$ruby_path creates=/usr/local/bin/ruby

- name: gem install
  command: /usr/local/bin/gem install {{ item }}
  with_items:
    - bundler
    - passenger
    - capistrano
    - puma
